kind: Backstage
apiVersion: rhdh.redhat.com/v1alpha3
metadata:
  labels:
    app.kubernetes.io/name: backstage
  name: developer-hub
  namespace: developer-hub
spec:
  deployment:
    patch:
      spec:
        template:
          spec:
            automountServiceAccountToken: true
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root
  application:
    replicas: 1              # optional: scale up
    resources:                 # resources for the Backstage backend pod
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"

    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
         - name: developer-hub-core-config
         - name: my-rhdh-app-config
    extraEnvs:
      secrets:
         - name: rhdh-credentials
      envs:
        - name: LOG_LEVEL
          value: debug   
    extraFiles:
      mountPath: /opt/app-root/src
    route:
      enabled: true
      host: rhdh.apps.sno.neat-monster.com
    dynamicPluginsConfigMapName: dynamic-plugins-cm  
  database:
    enableLocalDb: true  
