kind: Backstage
apiVersion: rhdh.redhat.com/v1alpha3
metadata:
  labels:
    app.kubernetes.io/name: backstage
  name: developer-hub
  namespace: developer-hub
spec:
  deployment:
    patch:
      spec:
        template:
          spec:
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
         - name: developer-hub-core-config
         - name: my-rhdh-app-config
    extraEnvs:
      secrets:
         - name: rhdh-credentials
      envs:
        - name: LOG_LEVEL
          value: debug   
    extraFiles:
      mountPath: /opt/app-root/src
    route:
      enabled: true
    dynamicPluginsConfigMapName: dynamic-plugins-cm  
  database:
    enableLocalDb: true  