kind: Backstage
apiVersion: rhdh.redhat.com/v1alpha3
metadata:
  labels:
    app.kubernetes.io/name: backstage
  name: acme-developer-hub
  namespace: acme-developer-hub
spec:
  deployment:
    patch:
      spec:
        template:
          spec:
            automountServiceAccountToken: true
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
         - name: developer-hub-core-config
         - name: acme-app-config
    extraEnvs:
      secrets:
         - name: acme-dh-credentials
      envs:
        - name: LOG_LEVEL
          value: warn   
    extraFiles:
      mountPath: /opt/app-root/src
      configMaps:
        - name: rbac-policies  
    route:
      enabled: true
    dynamicPluginsConfigMapName: acme-dynamic-plugins-cm  
  database:
    enableLocalDb: true  
